export default function Terms() {
  return (
    <div style={{
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      maxWidth: 720,
      margin: "0 auto",
      padding: "40px 20px 80px",
      lineHeight: 1.6,
      color: "#1a1a1a",
    }}>
      <h1 style={{ fontSize: 28, marginBottom: 4 }}>Terms of Service</h1>
      <p style={{ color: "#777", fontSize: 14, marginBottom: 32 }}>Last updated: July 9, 2026</p>

      <p>Welcome to GoPackNow ("we," "us," or "our"). By using our app or website at gopack.now (the "Service"), you agree to these Terms of Service. Please read them carefully.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>1. Eligibility</h2>
      <p>You must be at least 13 years old to use the Service. By using GoPackNow you represent that you meet this requirement and that you have the legal capacity to enter into these Terms.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>2. Account</h2>
      <p>You may sign in with Google or as a guest. You are responsible for all activity that occurs under your account. Notify us immediately at <a href="mailto:support@gopack.now" style={{ color: "#E85D3A" }}>support@gopack.now</a> if you suspect unauthorized use.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>3. Subscriptions &amp; Payments</h2>
      <p>GoPackNow offers optional paid subscriptions ("GoPackNow Plus") processed by Paddle.com, our Merchant of Record. By subscribing you agree to Paddle's <a href="https://www.paddle.com/legal/checkout-buyer-terms" style={{ color: "#E85D3A" }} target="_blank" rel="noopener noreferrer">Buyer Terms</a>. Subscription fees are charged at the start of each billing period. You may cancel anytime; access continues until the end of the paid period. See our <a href="/refunds" style={{ color: "#E85D3A" }}>Refund Policy</a> for details.</p>
      <p>One subscription unlocks GoPackNow Plus for every member of a specific trip ("group unlock"). The unlock applies only to that trip.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul style={{ paddingLeft: 22 }}>
        <li>Upload or share content that is unlawful, offensive, or violates anyone's rights</li>
        <li>Attempt to reverse-engineer, scrape, or disrupt the Service</li>
        <li>Use the Service to send spam or unsolicited communications</li>
        <li>Circumvent any access controls or usage limits</li>
      </ul>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>5. AI-Generated Content</h2>
      <p>Itineraries and packing lists are generated by AI (Anthropic Claude) and are provided for planning purposes only. We make no guarantees about their accuracy, availability of venues, pricing, or fitness for any particular trip. Always verify important details independently.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>6. Intellectual Property</h2>
      <p>The GoPackNow brand, design, and software are owned by us. Content you create (trip data, wishlist items, chat messages) remains yours. You grant us a limited licence to store and display it to your trip members as needed to operate the Service.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>7. Disclaimers</h2>
      <p>The Service is provided "as is" without warranty of any kind. We do not guarantee uninterrupted availability or operation without errors.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>8. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law, GoPackNow's total liability to you for any claim arising from these Terms or your use of the Service is limited to the amount you paid us in the 12 months preceding the claim, or £50, whichever is greater.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>9. Changes to These Terms</h2>
      <p>We may update these Terms from time to time. Continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.</p>

      <h2 style={{ fontSize: 20, marginTop: 36, marginBottom: 10 }}>10. Contact</h2>
      <div style={{ background: "#f7f7f7", borderRadius: 10, padding: "16px 20px", marginTop: 12 }}>
        <p style={{ margin: 0 }}>Questions? Reach us at:</p>
        <p style={{ margin: "4px 0 0" }}>
          <a href="mailto:support@gopack.now" style={{ color: "#E85D3A" }}>support@gopack.now</a>
        </p>
      </div>
    </div>
  );
}
