const colors = {
  light: {
    text: "#1A1412",
    tint: "#E85D3A",
    background: "#FAF8F5",
    foreground: "#1A1412",
    card: "#FFFDF9",
    cardForeground: "#1A1412",
    primary: "#E85D3A",
    primaryForeground: "#FFFFFF",
    secondary: "#F0EAE0",
    secondaryForeground: "#1A1412",
    muted: "#E8E2D6",
    mutedForeground: "#7A6E66",
    accent: "#E85D3A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DAD5CC",
    input: "#DAD5CC",
  },
  dark: {
    text: "#FAF8F5",
    tint: "#E85D3A",
    background: "#1A1412",
    foreground: "#FAF8F5",
    card: "#211C19",
    cardForeground: "#FAF8F5",
    primary: "#E85D3A",
    primaryForeground: "#FFFFFF",
    secondary: "#2A2320",
    secondaryForeground: "#FAF8F5",
    muted: "#2A2320",
    mutedForeground: "#BDB0A0",
    accent: "#E85D3A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#332E2B",
    input: "#332E2B",
  },
  radius: 8,
};

export default colors;
