const colors = {
  light: {
    text: "#0E0D0B",
    tint: "#E85D3A",
    background: "#FFFDF9",
    foreground: "#0E0D0B",
    card: "#FFFFFF",
    cardForeground: "#0E0D0B",
    primary: "#E85D3A",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F0E8",
    secondaryForeground: "#0E0D0B",
    muted: "#EDE8DE",
    mutedForeground: "#756C66",
    accent: "#E85D3A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E8E4DC",
    input: "#E8E4DC",
  },
  dark: {
    text: "#FFFDF9",
    tint: "#E85D3A",
    background: "#0E0D0B",
    foreground: "#FFFDF9",
    card: "#141110",
    cardForeground: "#FFFDF9",
    primary: "#E85D3A",
    primaryForeground: "#FFFFFF",
    secondary: "#221D1A",
    secondaryForeground: "#FFFDF9",
    muted: "#221D1A",
    mutedForeground: "#BDB0A0",
    accent: "#E85D3A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#332E2B",
    input: "#332E2B",
  },
  radius: 8,
};

export default colors;
