const colors = {
  light: {
    text: "#241F1B",
    tint: "#F15A3A",
    background: "#FCFBF8",
    foreground: "#241F1B",
    card: "#FFFFFF",
    cardForeground: "#241F1B",
    primary: "#F15A3A",
    primaryForeground: "#FFFFFF",
    secondary: "#F6F1EA",
    secondaryForeground: "#241F1B",
    muted: "#F0EBE4",
    mutedForeground: "#827A73",
    accent: "#F4BC55",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E8E1D9",
    input: "#E8E1D9",
  },
  dark: {
    text: "#FCFBF8",
    tint: "#F15A3A",
    background: "#241F1B",
    foreground: "#FCFBF8",
    card: "#302A25",
    cardForeground: "#FCFBF8",
    primary: "#F15A3A",
    primaryForeground: "#FFFFFF",
    secondary: "#382F29",
    secondaryForeground: "#FCFBF8",
    muted: "#382F29",
    mutedForeground: "#C9BEB2",
    accent: "#F4BC55",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#4A4038",
    input: "#4A4038",
  },
  radius: 14,
};

export default colors;
